Add ROS_DOMAIN_ID minor fixes in nanosaur script

diff --git a/nanosaur/scripts/nanosaur b/nanosaur/scripts/nanosaur
--- a/nanosaur/scripts/nanosaur
+++ b/nanosaur/scripts/nanosaur
@@ -39,7 +39,7 @@ if [ -f $NANOSAUR_DATA/.env ] ; then
 fi
 
 # Default variable
-NANOSAUR_VERSION='1.5.0'
+NANOSAUR_VERSION='1.5.1'
 ROBOT_NAME='nanosaur'
 NANOSAUR_WORKSPACE=$HOME/$ROS_WS_NAME
 
@@ -60,6 +60,9 @@ config_info()
     echo " - ${bold}Tag:${reset} ${green}$DOCKER_TAG${reset}" >&2
     echo " - ${bold}Network:${reset} ${green}$DOCKER_NETWORK${reset}" >&2
     echo " - ${bold}ROS distro:${reset} ${green}$ROS_DISTRO${reset}" >&2
+    if [ ! -z ${ROS_DOMAIN_ID+x} ] ; then
+        echo " - ${bold}ROS_DOMAIN_ID:${reset} ${green}$ROS_DOMAIN_ID${reset}" >&2
+    fi
 }
 
 config_save()
@@ -68,6 +71,9 @@ config_save()
     echo "DOCKER_TAG=$DOCKER_TAG" > $NANOSAUR_DATA/.env
     echo "DOCKER_NETWORK=$DOCKER_NETWORK" >> $NANOSAUR_DATA/.env
     echo "ROS_DISTRO=$ROS_DISTRO" >> $NANOSAUR_DATA/.env
+    if [ ! -z ${ROS_DOMAIN_ID+x} ] ; then
+        echo "ROS_DOMAIN_ID=$ROS_DOMAIN_ID" >> $NANOSAUR_DATA/.env
+    fi
 }
 
 get_rosinstall()
@@ -122,6 +128,7 @@ usage()
     echo "Commands:" >&2
     echo "  $name version               Version" >&2
     echo "  $name info                  Status" >&2
+    echo "  $name domain                Set ROS_DOMAIN_ID" >&2 # https://docs.ros.org/en/ros2_documentation/foxy/Concepts/About-Domain-ID.html
     echo "  $name install  [dev]        Install nanosaur environment. ${bold}dev${reset} enable developer mode" >&2
     if [[ $PLATFORM = "aarch64" ]]; then
         echo "  $name update                Update docker and scripts" >&2
@@ -130,10 +137,11 @@ usage()
         echo "  $name network [host/bridge] Select network configuration" >&2
         echo "  $name config                Open/create nanosaur.yml in ${bold}$NANOSAUR_DATA/param${reset} (use nano)" >&2
         echo " "  >&2
+        echo "  $name wakeup                start nanosaur systems (eq. nanosaur up -d)" >&2
         echo "  $name [start/restart/stop/up/down/logs]  Control nanosaur docker" >&2
     else
-        echo "  $name update      Update all robot workspace" >&2
-        echo "  $name activate    Load all variables and workspaces for nanosaur" >&2
+        echo "  $name update                Update all robot workspace" >&2
+        echo "  $name activate              Load all variables and workspaces for nanosaur" >&2
     fi
 }
 
@@ -359,7 +367,7 @@ installer()
         mkdir -p "$NANOSAUR_DATA/param"
     fi
 
-    if $developer ; then
+    if $developer || [[ $PLATFORM = "x86_64" ]] ; then
 
         if ! command -v vcs &> /dev/null ; then
             echo " - Install vcs tool"
@@ -505,6 +513,28 @@ main()
         # Update nanosaur
         update $arguments
         exit 0
+    elif [ $option = "domain" ] ; then
+        # https://docs.ros.org/en/ros2_documentation/foxy/Concepts/About-Domain-ID.html
+        if [ ! -z "$arguments" ] ; then
+            # Check if is a number
+            local re='^[0-9]+$'
+            if ! [[ $arguments =~ $re ]] ; then
+                echo "${red}error: Not a number${reset}" >&2
+                exit 1
+            fi
+            # Set ROS_DOMAIN_ID
+            ROS_DOMAIN_ID=$arguments
+            config_save
+        fi
+        # Read ROS_DOMAIN_ID variable
+        local domain=0
+        if [ -z ${ROS_DOMAIN_ID+x} ] ; then
+            echo "${yellow}Unset variable${reset}"
+        else
+            domain=$ROS_DOMAIN_ID
+        fi
+        echo "ROS_DOMAIN_ID=$domain"
+        exit 0
     fi
     # Desktop options
     if [ $PLATFORM = "x86_64" ] ; then
@@ -591,6 +621,8 @@ main()
             docker-compose -f $NANOSAUR_DATA/docker-compose.yml stop $arguments
         elif [ $option = "down" ] ; then
             docker-compose -f $NANOSAUR_DATA/docker-compose.yml down $arguments
+        elif [ $option = "wakeup" ] ; then
+            docker-compose -f $NANOSAUR_DATA/docker-compose.yml up -d
         else
             usage "[ERROR] Unknown option: $option" >&2
             exit 1
